defaults:
  - _self_
  - actor_extractor: extractor
  - critic_extractor: extractor
  - actor_head: independent_std_head
  - critic_head: scalar_head


_target_: configs.network.SeparatedArchitectureConfig