defaults:
  - _self_
  - env: bipedal_walker
  - agent: continuous
  - algorithm: ppo
  - buffer: rollout
  - runner: on_policy
  - optimizer: ppo_optimizer
  - logger: tensor_board_logger

_target_: configs.train.TrainConfig
seed: 42