defaults:
  - _self_
  - env: bipedal_walker
  - agent: continuous
  - algorithm: ppo
  - buffer: rollout
  - runner: on_policy
  - optimizer: ppo_optimizer
  - logger: ppo_logger
  - trainer: on_policy_traner

_target_: configs.train.TrainConfig
seed: 42
checkpoint_path: checkpoints/on_policy/2026-01-17/23-25-43/checkpoint_1100.pth